_target_: src.models.tsr_basemodule.TSRBaseModule

net:
  _target_: src.models.components.lr_cond_unet.LRCondUNet
  hr_size: 224
  lr_emb_size: 128
  text_emb_size: 128

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 5e-4
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: 200
  eta_min: 1e-5
  # mode: max
  # factor: 0.1
  # patience: 5


# compile model for faster training with pytorch 2.0
compile: false
