_target_: src.models.tsr_basemodule.TSRBaseModule

net:
  _target_: src.models.components.conditional_unet.ConditionalUNet
  hr_size: 224
  lr_emb_size: 128
  text_emb_size: 0
  layers_per_block: 2
  block_out_channels: [32, 64, 128]
  down_block_types: ["DownBlock2D", "DownBlock2D", "DownBlock2D"]
  up_block_types: ["UpBlock2D", "UpBlock2D", "UpBlock2D"]

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-3


scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: ${trainer.max_epochs}
  eta_min: 1e-5

# compile model for faster training with pytorch 2.0
compile: false

diff_steps: 1000
txt2img_similarity: false
img2img_similarity: false