_target_: src.models.tsr_basemodule.TSRBaseModule

net:
  _target_: src.models.components.clip_sr.CLIPSR
  hr_size: 224


optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.1
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10


# compile model for faster training with pytorch 2.0
compile: false
